In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

C:\Users\l_san\AppData\Local\Continuum\anaconda3\lib\site-packages\setuptools\_importlib.py:23: UserWarning: `importlib-metadata` version is incompatible with `setuptools`.
This problem is likely to be solved by installing an updated version of `importlib-metadata`.
  warnings.warn(msg)  # Ensure a descriptive message is shown.
C:\Users\l_san\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\compat\_optional.py:138: UserWarning: Pandas requires version '2.7.0' or newer of 'numexpr' (version '2.6.9' currently installed).
  warnings.warn(msg, UserWarning)

Bad key text.latex.preview in file C:\Users\l_san\AppData\Local\Continuum\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 123 ('text.latex.preview : False')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.5.3/matplotlibrc.template
or from the matplotlib source distribution

Bad key mathtext.fallback_to_cm in file C:\Users\l_san\Ap

In [2]:
reviews = pd.read_csv('../Datasets/movie_reviews_clean.csv')
reviews.head()

review  sentiment
0  this anime series starts out great interesting...          0
1  some may go for a film like this but i most as...          0
2  i ve seen this piece of perfection during the ...          1
3  this movie is likely the worst movie i ve ever...          0
4  it ll soon be 10 yrs since this movie was rele...          1

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
X_train, X_test, y_train, y_test = train_test_split(reviews['review'], reviews['sentiment'],test_size=0.2)

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [6]:
vec = TfidfVectorizer(stop_words='english', strip_accents='ascii' )

In [7]:
matrix_train = vec.fit_transform(X_train)

In [8]:
matrix_test = vec.transform(X_test)

In [9]:
from sklearn.naive_bayes import MultinomialNB

In [10]:
from sklearn.svm import SVC

In [11]:
model = SVC()

In [12]:
model.fit(matrix_train, y_train)

SVC()

In [13]:
model.score(matrix_test, y_test)

0.79

In [14]:
vec2 = TfidfVectorizer(stop_words='english', strip_accents='ascii', ngram_range=(1,2))

In [15]:
matrix2_train = vec2.fit_transform(X_train)

In [16]:
matrix2_test = vec2.transform(X_test)

In [17]:
model2 = SVC()

In [18]:
model2.fit(matrix2_train, y_train)

SVC()

In [19]:
model2.score(matrix2_test, y_test)

0.785

In [20]:
from sklearn.metrics.pairwise import cosine_similarity

In [21]:
A = [1,2,3,4,5,6,7,8]

In [22]:
B= [12,22,3345,22,5,87,654,6]

In [23]:
cosine_similarity([A], [B])

array([[0.31524222]])

In [24]:
C = [10,12,22,3,4,5,3,23]

In [25]:
cosine_similarity([A], [C])

array([[0.70830945]])

In [26]:
from sklearn.metrics.pairwise import linear_kernel

In [27]:
movies = pd.read_csv('../Datasets/movie_overviews.csv')

In [28]:
movies.head()

id                        title  \
0    862                    Toy Story   
1   8844                      Jumanji   
2  15602             Grumpier Old Men   
3  31357            Waiting to Exhale   
4  11862  Father of the Bride Part II   

                                            overview  \
0  Led by Woody, Andy's toys live happily in his ...   
1  When siblings Judy and Peter discover an encha...   
2  A family wedding reignites the ancient feud be...   
3  Cheated on, mistreated and stepped on, the wom...   
4  Just when George Banks has recovered from his ...   

                                             tagline  
0                                                NaN  
1          Roll the dice and unleash the excitement!  
2  Still Yelling. Still Fighting. Still Ready for...  
3  Friends are the people who let you be yourself...  
4  Just When His World Is Back To Normal... He's ...

In [29]:
indices = pd.Series(movies.index, index=movies['title'])
indices.head()

title
Toy Story                      0
Jumanji                        1
Grumpier Old Men               2
Waiting to Exhale              3
Father of the Bride Part II    4
dtype: int64

In [30]:
tfidf = TfidfVectorizer(stop_words='english', strip_accents='ascii')

In [31]:
movies.dropna(inplace=True)

In [32]:
import spacy

In [33]:
nlp = spacy.load('en_core_web_sm')

In [34]:
def get_lemma(string):
    doc = nlp(string)
    lemmas= [text.lemma_ for text in doc]
    return (' '.join(lemmas))

In [35]:
movies['lemmas'] = movies['overview'].apply(get_lemma)

In [36]:
movies.head()

id                        title  \
1   8844                      Jumanji   
2  15602             Grumpier Old Men   
3  31357            Waiting to Exhale   
4  11862  Father of the Bride Part II   
5    949                         Heat   

                                            overview  \
1  When siblings Judy and Peter discover an encha...   
2  A family wedding reignites the ancient feud be...   
3  Cheated on, mistreated and stepped on, the wom...   
4  Just when George Banks has recovered from his ...   
5  Obsessive master thief, Neil McCauley leads a ...   

                                             tagline  \
1          Roll the dice and unleash the excitement!   
2  Still Yelling. Still Fighting. Still Ready for...   
3  Friends are the people who let you be yourself...   
4  Just When His World Is Back To Normal... He's ...   
5                           A Los Angeles Crime Saga   

                                              lemmas  
1  when sibling Judy and Peter discover an enchan...  
2  a family wedding reignite the ancient feud bet...  
3  cheat on , mistreat and step on , the woman be...  
4  just when George Banks have recover from his d...  
5  obsessive master thief , Neil McCauley lead a ...

In [37]:
tfidf_matrix = tfidf.fit_transform(movies['lemmas'])

In [38]:
dot_mat = linear_kernel(tfidf_matrix, tfidf_matrix)

In [39]:
dot_mat

array([[1.        , 0.04410054, 0.        , ..., 0.00947086, 0.0068802 ,
        0.01108132],
       [0.04410054, 1.        , 0.        , ..., 0.        , 0.00834195,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.00893207, 0.        ,
        0.        ],
       ...,
       [0.00947086, 0.        , 0.00893207, ..., 1.        , 0.        ,
        0.        ],
       [0.0068802 , 0.00834195, 0.        , ..., 0.        , 1.        ,
        0.0055484 ],
       [0.01108132, 0.        , 0.        , ..., 0.        , 0.0055484 ,
        1.        ]])

In [40]:
dot_mat[5]

array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
       0.06288928])

In [41]:
indices['Heat']

5

In [42]:
def get_movies(title, matrix, indices):
    index = indices[title]
    Lis = list(enumerate(matrix[index]))
    Lis_sor = sorted(Lis, key= lambda x:x[1], reverse=True)
    indices = [indice[0] for indice in Lis_sor]
    return indices[1:8]
    

In [43]:
mo_lis = get_movies('Heat', dot_mat, indices)
mo_lis

[1937, 1037, 6671, 4433, 4985, 5728, 1214]

In [44]:
indices.head()

title
Toy Story                      0
Jumanji                        1
Grumpier Old Men               2
Waiting to Exhale              3
Father of the Bride Part II    4
dtype: int64

In [45]:
movies.iloc[mo_lis]

id                      title  \
2331   13824                  Superstar   
1267   49462               Career Girls   
8602  210577                  Gone Girl   
5569  104659  A Small Circle of Friends   
6366   10073                 Date Movie   
7342   24684               An Education   
1484  102304                   Whatever   

                                               overview  \
2331  Orphan Mary Katherine Gallagher, an ugly duckl...   
1267  Two young women reunite and rekindle their fri...   
8602  With his wife's disappearance having become th...   
5569  In the late 1960s, three Harvard students Jess...   
6366  Spoof of romantic comedies which focuses on a ...   
7342  A coming-of-age story about a teenage girl in ...   
1484  A teen faces her impending adulthood in the ca...   

                                                tagline  \
2331                                     Dare to dream.   
1267  This Holiday Weekend spend in the company of w...   
8602        You don't know what you've got 'til it's...   
5569  The story of three people and the era that sha...   
6366                              An Unprotected Comedy   
7342             An education isn't always by the book.   
1484     1981. In an era of just say no, they said yes.   

                                                 lemmas  
2331  Orphan Mary Katherine Gallagher , an ugly duck...  
1267  two young woman reunite and rekindle their fri...  
8602  with his wife 's disappearance having become t...  
5569  in the late 1960 , three Harvard student Jessi...  
6366  spoof of romantic comedy which focus on a man ...  
7342  a come - of - age story about a teenage girl i...  
1484  a teen face her impending adulthood in the car...

In [62]:
movies.shape

(7033, 5)

In [64]:
movies.head()

id                        title  \
1   8844                      Jumanji   
2  15602             Grumpier Old Men   
3  31357            Waiting to Exhale   
4  11862  Father of the Bride Part II   
5    949                         Heat   

                                            overview  \
1  When siblings Judy and Peter discover an encha...   
2  A family wedding reignites the ancient feud be...   
3  Cheated on, mistreated and stepped on, the wom...   
4  Just when George Banks has recovered from his ...   
5  Obsessive master thief, Neil McCauley leads a ...   

                                             tagline  \
1          Roll the dice and unleash the excitement!   
2  Still Yelling. Still Fighting. Still Ready for...   
3  Friends are the people who let you be yourself...   
4  Just When His World Is Back To Normal... He's ...   
5                           A Los Angeles Crime Saga   

                                              lemmas  
1  when sibling Judy and Peter discover an enchan...  
2  a family wedding reignite the ancient feud bet...  
3  cheat on , mistreat and step on , the woman be...  
4  just when George Banks have recover from his d...  
5  obsessive master thief , Neil McCauley lead a ...

In [86]:
movies.drop_duplicates(inplace=True)

In [89]:
movies.shape

(7027, 5)

In [91]:
indi = pd.Series(ni, index=movies['title'])
indi.head()

title
Jumanji                        0
Grumpier Old Men               1
Waiting to Exhale              2
Father of the Bride Part II    3
Heat                           4
dtype: int32

In [92]:
indi.shape

(7027,)

In [93]:
ni = np.arange(0,7027)

In [96]:
indi['Batman']

title
Batman     425
Batman    4552
dtype: int32

In [97]:
tfidf_vec2 = TfidfVectorizer(stop_words='english', strip_accents='ascii')

In [98]:
tfidf_mat2 = tfidf_vec2.fit_transform(movies['lemmas'])

In [99]:
cos2 = linear_kernel(tfidf_mat2, tfidf_mat2)
cos2[:5]

array([[1.        , 0.04409842, 0.        , ..., 0.00947978, 0.00689535,
        0.01109544],
       [0.04409842, 1.        , 0.        , ..., 0.        , 0.00834809,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.00894479, 0.        ,
        0.        ],
       [0.        , 0.02819675, 0.        , ..., 0.01228722, 0.        ,
        0.0273893 ],
       [0.05084406, 0.        , 0.00763711, ..., 0.        , 0.        ,
        0.00907336]])

In [100]:
cos2[100]

array([0.        , 0.00825113, 0.01433503, ..., 0.        , 0.        ,
       0.01428131])

In [101]:
def get_rec(title, matrix, indices):
    ind = indices[title]
    nm= list(enumerate(matrix[ind]))
    nm= sorted(nm, key= lambda x : x[1], reverse=True)
    ind2 = [zahl[0] for zahl in nm]
    return ind2[1:10]

In [103]:
movies.iloc[get_rec('The Dark Knight Rises', cos2, indi)]

id                                    title  \
6907     155                          The Dark Knight   
132      414                           Batman Forever   
1116     364                           Batman Returns   
524      268                                   Batman   
7573   40662               Batman: Under the Red Hood   
8171  123025  Batman: The Dark Knight Returns, Part 1   
7907   69735                         Batman: Year One   
2581   14919             Batman: Mask of the Phantasm   
4494   31598                                    Q & A   

                                               overview  \
6907  Batman raises the stakes in his war on crime. ...   
132   The Dark Knight of Gotham City confronts a das...   
1116  Having defeated the Joker, Batman now faces th...   
524   The Dark Knight of Gotham City begins his war ...   
7573  Batman faces his ultimate challenge as the mys...   
8171  Batman has not been seen for ten years. A new ...   
7907  Two men come to Gotham City: Bruce Wayne after...   
2581  An old flame of Bruce Wayne's strolls into tow...   
4494  A young district attorney seeking to prove a c...   

                                                tagline  \
6907                                    Why So Serious?   
132                        Courage now, truth always...   
1116                     The Bat, the Cat, the Penguin.   
524   Have you ever danced with the devil in the pal...   
7573                     Dare to Look Beneath the Hood.   
8171        Old heroes never die. They just get darker.   
7907      A merciless crime turns a man into an outlaw.   
2581  The Dark Knight fights to save Gotham city fro...   
4494  When the questions are dangerous, the answers ...   

                                                 lemmas  
6907  Batman raise the stake in his war on crime . w...  
132   the Dark Knight of Gotham City confront a dast...  
1116  having defeat the Joker , Batman now face the ...  
524   the Dark Knight of Gotham City begin his war o...  
7573  Batman face his ultimate challenge as the myst...  
8171  Batman have not be see for ten year . a new br...  
7907  two man come to Gotham City : Bruce Wayne afte...  
2581  an old flame of Bruce Wayne 's stroll into tow...  
4494  a young district attorney seek to prove a case...

In [104]:
nlp2 = spacy.load('en_core_web_lg')

OSError: [E050] Can't find model 'en_core_web_lg'. It doesn't seem to be a Python package or a valid path to a data directory.

In [105]:
spacy.cli.download("en_core_web_lg")

✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')


In [106]:
nlp2 = spacy.load('en_core_web_lg')

In [110]:
satz1 = nlp2('I am hungry')
satz2 = nlp2('I am horny')
satz3= nlp2('I could eat')

In [111]:
satz2.similarity(satz1)

0.9811052442122896

In [112]:
satz1.similarity(satz3)

0.7271272487678404